### ISSUE TITLE
版本说明与未来计划

### ISSUE THREAD

**Issue by chihqiang** [tp5er/tp5-databackup#10]
0.0.1 支持thinkphp5
0.1.0 支持thinkphp5 和 thinkphp5.1
1.0.0 支持thinkphp5,thinkphp5.1,thinkphp6
2.x 计划完全支持thinkphp6 不再向下兼容

**Comment by bmkj** [comment]
老大，什么时候支持PHP8.1？

**Comment by chihqiang** [comment]
> 老大，什么时候支持PHP8.1？
已亲测 #14 
参考：tp6-controller/index.php,如果您是因为需要完整的代码，请参考tp5-demo代码自行修改
开源包 只保证src目录下的文件是否可用，不保证其他目录下文件是否可用

**Comment by chihqiang** [comment]
#16

**Comment by chihqiang** [comment]
跨数据库进行备份还原 #19
