### ISSUE TITLE
能否做一个支持不同数据库的备份功能

### ISSUE THREAD

**Issue by yinjisong** [tp5er/tp5-databackup#19]
比如说传入一个数据库配置，可以远程拉取这个数据库的内容进行备份

**Comment by chihqiang** [comment]
你可以尝试一下主分支代码 `composer require tp5er/tp5-databackup dev-main`

可以参考垮数据库备份    [脚本的方式进行交互式备份与还原](https://github.com/pkg6/tp5-databackup/blob/2ff3362a591974de9d7c03fd5a9a9edf33e32257/src/commands/BackupCommand.php#L18)

**Comment by chihqiang** [comment]
2024年4月18日 即将发布2.1.0调整完毕,你可以在dev-main 进行开发调试，本人已调整完毕

**Comment by chihqiang** [comment]
使用database方法进行切换数据库目前只支持mysql 如果你要备份其他类型的sql 可以参考[BuildSQLInterface](https://github.com/pkg6/think-backup/blob/main/src/build/BuildSQLInterface.php)实现 并通过setBuildSQL方法进行注入
