### ISSUE TITLE
老大，不支持PHP8.0和8.1噢

### ISSUE THREAD

**Issue by bmkj** [tp5er/tp5-databackup#9]
老大，不支持PHP8.0和8.1噢
我的环境：windows+apache+tp6.1+php8.0/8.1

**Comment by chihqiang** [comment]
目前thinkphp6.1 是可以进行使用的，本人目前所有的php环境都在7.4以下，如果你需要支持支持php8以上 可以自行修改源代码然后进行提交pull requests合并请求

**Comment by chihqiang** [comment]
会在这个计划中 #10
